  - name: Obtain Login
    include_vars: pass.yaml

  - name: Define TT Datacenter Core Router Provider
    set_fact:
      provider:
        host: "{{ inventory_hostname }}"
        username: "{{ creds['username'] }}"
        password: "{{ creds['password'] }}"
        auth_pass: "{{ creds['auth_pass'] }}"

  - name: TT Datacenter Core Router Config
    nxos_command:
      provider: "{{ provider }}"
      authorize: yes
      src: "~/Don-RePo/roles/tt-dc-core/files/tt-dc-core.cfg"