  - name: Obtain Login
    include_vars: pass.yaml

  - name: Define TT Los Angeles Router1 Provider
    set_fact:
      provider:
        host: "{{ inventory_hostname }}"
        username: "{{ creds['username'] }}"
        password: "{{ creds['password'] }}"
        auth_pass: "{{ creds['auth_pass'] }}"

  - name: TT Los Angeles Router1 Config
    ios_config:
      provider: "{{ provider }}"
      authorize: yes
      src: "~/Don-RePo/roles/tt-la-rt1/files/tt-la-rt1.cfg"