  - name: Obtain Login
    include_vars: pass.yaml

  - name: Define Edge1 Provider
    set_fact:
      provider:
        host: "{{ inventory_hostname }}"
        username: "{{ creds['username'] }}"
        password: "{{ creds['password'] }}"
        auth_pass: "{{ creds['auth_pass'] }}"

  - name: MTS Leaf1 Config
    nxos_config:
      provider: "{{ provider }}"
      authorize: yes
      src: "~/github/don-repo/roles/mts-edge1/files/tt-dc-core.cfg"