  - name: Obtain Login
    include_vars: pass.yaml

  - name: Define TT Datacenter Router2 Provider
    set_fact:
      provider:
        host: "{{ inventory_hostname }}"
        username: "{{ creds['username'] }}"
        password: "{{ creds['password'] }}"
        auth_pass: "{{ creds['auth_pass'] }}"

  - name: TT Datacenter Router2 Config
    ios_config:
      provider: "{{ provider }}"
      authorize: yes
      src: "~/Don-RePo/roles/tt-dc-rt2/files/tt-dc-rt2.cfg"