---
# tasks file for TT Chicago Switch
- name: Obtain Login
  include_vars: pass.yaml

- name: Define TT Los Anteles Switch1 Provider
  set_fact:
    provider:
      host: "{{ inventory_hostname }}"
      username: "{{ creds['username'] }}"
      password: "{{ creds['password'] }}"
      auth_pass: "{{ creds['auth_pass'] }}"

- include: tt-chi-sw1-config.yaml
