---
- hosts: att-peer2
  gather_facts: no
  connection: local

  tasks:
  - name: Obtain Login
    include_vars: pass.yaml

  - name: Define Provider
    set_fact:
      provider:
        host: "{{ inventory_hostname }}"
        username: "{{ creds['username'] }}"
        password: "{{ creds['password'] }}"
        auth_pass: "{{ creds['auth_pass'] }}"

  - name: Switch Interface Config
    ios_config:
      provider: "{{ provider }}"
      authorize: yes
      lines:
         - router bgp 2018
         - bgp log-neighbor-changes
         - neighbor {{ verizonpeer1pop1 }} remote-as 2735
         - neighbor {{ verizonpeer1pop1 }} description eBGP to Verizon-Peer1
         - neighbor {{ coxpeerpop1 }} remote-as 1950
         - neighbor {{ coxpeerpop1 }} description eBGP to Level3-Peer
         - neighbor {{ verizonpeer2pop1 }} remote-as 2735
         - neighbor {{ verizonpeer2pop1 }}  description eBGP to Verizon-Peer2
         - neighbor {{ attpeer1internal }} remote-as 2018
         - neighbor {{ attpeer1internal }}  description iBGP peer ATT-Per2
         - neighbor {{ attpeer1internal }}  update-source Loopback0
         - neighbor {{ comcastpeerpop1 }} remote-as 1950
         - neighbor {{ comcastpeerpop1 }} description eBGP to Level3-Peer
         - address-family ipv4
         - network 67.40.0.0 mask 255.255.0.0
         - network 68.5.0.0 mask 255.255.0.0
         - network 69.20.0.0 mask 255.255.0.0
         - network 68.100.20.0 mask 255.255.255.0
         - network 68.100.21.0 mask 255.255.255.0
         - neighbor {{ verizonpeer1pop1 }} activate
         - neighbor {{ verizonpeer1pop1 }} send-community
         - neighbor {{ coxpeerpop1 }} activate
         - neighbor {{ coxpeerpop1 }} send-community
         - neighbor {{ comcastpeerpop1 }} activate
         - neighbor {{ comcastpeerpop1 }} send-community
         - neighbor {{ verizonpeer2pop1 }} activate
         - neighbor {{ verizonpeer2pop1 }} send-community
         - neighbor {{ attpeer1internal }} activate
         - neighbor {{ attpeer1internal }} next-hop-self
      match: exact
